name: Labeler hotfix
on:
  pull_request:
    branches:
      - "hotfix/**"

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler-hotfix.yml"
